/**
 * fastExtract.ts — Client-Side Regex Extraction Engine
 * =====================================================
 * Deterministic, zero-API-cost extraction of statutory identifiers
 * from digital-text PDF content. Runs entirely in the browser.
 *
 * Extracts:
 *   - GSTIN  (15-char statutory format: 2-digit state + PAN + entity + Z + checksum)
 *   - IRN    (64-character lowercase hex Invoice Reference Number)
 *   - Invoice ID (alphanumeric with -, / separators, max 16 chars)
 */

export interface FastExtractResult {
  gst_no?: string;
  irn?: string;
  supplier_inv?: string;
  /** Which fields were extracted by the local regex engine */
  _extraction_source: Record<string, "regex">;
}

/* ── GSTIN ────────────────────────────────────────────────────────────────── */

/**
 * Indian GSTIN: 15 characters
 *   Pos 1-2:  State code (01–38)
 *   Pos 3-7:  PAN alpha (5 letters)
 *   Pos 8-11: PAN numeric (4 digits)
 *   Pos 12:   PAN alpha (1 letter)
 *   Pos 13:   Entity type (1-9 or A-Z)
 *   Pos 14:   Always "Z"
 *   Pos 15:   Check digit (0-9 or A-Z)
 */
const GSTIN_REGEX =
  /\b(0[1-9]|[12]\d|3[0-8])[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]\b/gi;

export function extractAllGSTINs(text: string): string[] {
  const matches = text.toUpperCase().match(GSTIN_REGEX);
  if (!matches) return [];
  // De-duplicate
  return [...new Set(matches.map((m) => m.toUpperCase()))];
}

export function extractFirstGSTIN(text: string): string | undefined {
  const all = extractAllGSTINs(text);
  return all.length > 0 ? all[0] : undefined;
}

/* ── IRN (Invoice Reference Number) ──────────────────────────────────────── */

/**
 * IRN is a 64-character hexadecimal string generated by the IRP.
 * Must be exactly 64 hex chars, word-boundary delimited.
 */
const IRN_REGEX = /\b([a-fA-F0-9]{64})\b/g;

export function extractAllIRNs(text: string): string[] {
  const matches = [...text.matchAll(IRN_REGEX)].map((m) => m[1].toLowerCase());
  return [...new Set(matches)];
}

export function extractFirstIRN(text: string): string | undefined {
  const all = extractAllIRNs(text);
  return all.length > 0 ? all[0] : undefined;
}

/* ── Invoice Number ──────────────────────────────────────────────────────── */

/**
 * Invoice numbers appear after keywords like "Invoice No", "Inv No",
 * "Bill No", "Debit Note No", "Tax Invoice No", etc.
 * Captures alphanumeric strings with -, /, \ separators, 1-16 chars.
 */
const INV_NO_REGEX =
  /(?:Invoice|Inv|Bill|Debit\s*Note|Credit\s*Note|Tax\s*Invoice|Proforma)[\s.]*(?:No|Number|#|Ref)?[\s.:#-]*([A-Za-z0-9][A-Za-z0-9\-/\\]{0,15})\b/gi;

export function extractInvoiceNumbers(text: string): string[] {
  const matches = [...text.matchAll(INV_NO_REGEX)].map((m) => m[1].trim());
  return [...new Set(matches)].filter((m) => m.length >= 2);
}

export function extractFirstInvoiceNumber(text: string): string | undefined {
  const all = extractInvoiceNumbers(text);
  return all.length > 0 ? all[0] : undefined;
}

/* ── Combined extraction ─────────────────────────────────────────────────── */

/**
 * Run all regex engines on a text block and return a combined result.
 * This is the primary entrypoint used by the invoice-extractor page.
 */
export function fastExtract(text: string): FastExtractResult {
  const result: FastExtractResult = {
    _extraction_source: {},
  };

  const gstin = extractFirstGSTIN(text);
  if (gstin) {
    result.gst_no = gstin;
    result._extraction_source["gst_no"] = "regex";
  }

  const irn = extractFirstIRN(text);
  if (irn) {
    result.irn = irn;
    result._extraction_source["irn"] = "regex";
  }

  const invNo = extractFirstInvoiceNumber(text);
  if (invNo) {
    result.supplier_inv = invNo;
    result._extraction_source["supplier_inv"] = "regex";
  }

  return result;
}
